### ISSUE TITLE
AttributeError: module 'majka' has no attribute 'Majka'

### ISSUE THREAD

**Issue by AmitMY** [petrpulc/python-majka#2]
I ran: `pip install majka`

And then tried the code from the README, with an English dictionary:

```python
import majka
morph = majka.Majka('lib/majka/w-lt.en.fsa')
```

Failed on the second line:
> AttributeError: module 'majka' has no attribute 'Majka'

**Comment by petrpulc** [comment]
I am unable to reproduce this error in traditional setup; are you sure that you have no colliding module named majka in your path?

Try:
```python
import majka
print(majka.__file__)
```

and compare the resulting path with output of
```
$ pip3 show majka
```

**Comment by petrpulc** [comment]
I suppose it solved your issue...
